export const ALL_NSE_STOCKS = [
  { symbol: "RELIANCE", name: "Reliance Industries Ltd.", sector: "Energy & Conglomerate", cap: "Large Cap", price: 2962.80, prevClose: 2874.60, marketCap: "₹ 19,94,018 Cr", peRatio: "25.24", divYield: "0.34%", high52: 3052.00, low52: 2210.00, description: "Reliance Industries Limited is an Indian multinational conglomerate company, headquartered in Mumbai. Its businesses include energy, petrochemicals, natural gas, retail, telecommunications, mass media, and textiles." },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd.", sector: "Information Technology", cap: "Large Cap", price: 3456.70, prevClose: 3410.20, marketCap: "₹ 12,65,410 Cr", peRatio: "28.15", divYield: "1.15%", high52: 4250.00, low52: 3120.00, description: "Tata Consultancy Services Limited is an Indian multinational information technology services and consulting company headquartered in Mumbai. It is a part of the Tata Group and operates in 150 locations across 46 countries." },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1731.55, prevClose: 1718.40, marketCap: "₹ 13,10,620 Cr", peRatio: "19.80", divYield: "1.05%", high52: 1790.00, low52: 1360.00, description: "HDFC Bank Limited is an Indian banking and financial services company headquartered in Mumbai. It is India's largest private sector bank by assets and the world's tenth-largest bank by market capitalization." },
  { symbol: "INFY", name: "Infosys Ltd.", sector: "Information Technology", cap: "Large Cap", price: 1412.30, prevClose: 1425.10, marketCap: "₹ 5,85,420 Cr", peRatio: "24.60", divYield: "2.30%", high52: 1760.00, low52: 1280.00, description: "Infosys Limited is an Indian multinational information technology company that provides business consulting, information technology and outsourcing services. The company was founded in Pune and is headquartered in Bangalore." },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1080.00, prevClose: 1092.50, marketCap: "₹ 7,55,240 Cr", peRatio: "17.40", divYield: "0.95%", high52: 1150.00, low52: 840.00, description: "ICICI Bank Limited is an Indian multinational bank and financial services company headquartered in Mumbai. It offers a wide range of banking products and financial services for corporate and retail customers." },
  { symbol: "LT", name: "Larsen & Toubro Ltd.", sector: "Engineering & Infrastructure", cap: "Large Cap", price: 3450.00, prevClose: 3422.00, marketCap: "₹ 4,85,600 Cr", peRatio: "35.10", divYield: "0.85%", high52: 3890.00, low52: 2150.00, description: "Larsen & Toubro Limited, commonly known as L&T, is an Indian multinational conglomerate company, with business interests in engineering, construction, manufacturing, technology, information technology and financial services." },
  { symbol: "ITC", name: "ITC Ltd.", sector: "FMCG", cap: "Large Cap", price: 480.00, prevClose: 478.20, marketCap: "₹ 5,95,210 Cr", peRatio: "26.80", divYield: "3.75%", high52: 510.00, low52: 390.00, description: "ITC Limited is an Indian conglomerate company headquartered in Kolkata. ITC has a diversified presence across industries such as FMCG, hotels, software, packaging, paperboards, specialty papers and agribusiness." },
  { symbol: "SBIN", name: "State Bank of India", sector: "Banking & Finance", cap: "Large Cap", price: 810.00, prevClose: 818.90, marketCap: "₹ 7,20,100 Cr", peRatio: "9.50", divYield: "1.65%", high52: 890.00, low52: 510.00, description: "State Bank of India is an Indian multinational public sector bank and financial services statutory body headquartered in Mumbai. SBI is the largest bank in India with a 23% asset market share." },
  { symbol: "WIPRO", name: "Wipro Ltd.", sector: "Information Technology", cap: "Large Cap", price: 485.00, prevClose: 482.50, marketCap: "₹ 2,53,400 Cr", peRatio: "21.40", divYield: "1.20%", high52: 545.00, low52: 375.00, description: "Wipro Limited is an Indian multinational corporation that provides information technology, consultant and business process services. It is headquartered in Bangalore, India." },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd.", sector: "Automotive", cap: "Large Cap", price: 955.00, prevClose: 945.20, marketCap: "₹ 3,17,200 Cr", peRatio: "15.80", divYield: "0.60%", high52: 1065.00, low52: 520.00, description: "Tata Motors Limited is an Indian multinational automotive manufacturing company headquartered in Mumbai. It is a leading global automobile manufacturer of cars, utility vehicles, buses, trucks, and defense vehicles." },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd.", sector: "Metals & Mining", cap: "Large Cap", price: 168.00, prevClose: 165.40, marketCap: "₹ 2,09,700 Cr", peRatio: "24.50", divYield: "2.10%", high52: 184.00, low52: 108.00, description: "Tata Steel Limited is an Indian multinational steel-making company, based in Jamshedpur, Jharkhand and headquartered in Mumbai, Maharashtra. It is one of the top steel producing companies globally." },
  { symbol: "ZOMATO", name: "Zomato Ltd.", sector: "Consumer Services", cap: "Large Cap", price: 198.50, prevClose: 194.20, marketCap: "₹ 1,75,400 Cr", peRatio: "120.50", divYield: "0.00%", high52: 210.00, low52: 72.00, description: "Zomato Limited is an Indian multinational restaurant aggregator and food delivery company. Zomato provides information, menus and user-reviews of restaurants as well as food delivery options from partner restaurants." },
  { symbol: "MRF", name: "MRF Ltd.", sector: "Automotive", cap: "Large Cap", price: 125000.00, prevClose: 124200.00, marketCap: "₹ 53,000 Cr", peRatio: "24.15", divYield: "0.15%", high52: 150000.00, low52: 93000.00, description: "Madras Rubber Factory (MRF) is an Indian multinational tyre manufacturing company and the largest manufacturer of tyres in India, headquartered in Chennai, Tamil Nadu." },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd.", sector: "FMCG", cap: "Large Cap", price: 2450.00, prevClose: 2465.00, marketCap: "₹ 5,75,800 Cr", peRatio: "56.20", divYield: "1.75%", high52: 2770.00, low52: 2170.00, description: "Hindustan Unilever Limited is a consumer goods company headquartered in Mumbai. It is a subsidiary of Unilever, offering food, beverages, cleaning agents, personal care products, and water purifiers." },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd.", sector: "Telecommunications", cap: "Large Cap", price: 1380.00, prevClose: 1362.50, marketCap: "₹ 8,12,400 Cr", peRatio: "42.10", divYield: "0.70%", high52: 1460.00, low52: 810.00, description: "Bharti Airtel Limited is an Indian multinational telecommunications services company based in New Delhi. It operates in 18 countries across South Asia and Africa, as well as the Channel Islands." },
  { symbol: "AXISBANK", name: "Axis Bank Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1120.00, prevClose: 1110.80, marketCap: "₹ 3,45,200 Cr", peRatio: "14.10", divYield: "0.10%", high52: 1220.00, low52: 910.00, description: "Axis Bank Limited is an Indian banking and financial services company headquartered in Mumbai, Maharashtra. It is India's third-largest private sector bank by assets and fourth-largest by market capitalization." },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1740.00, prevClose: 1752.00, marketCap: "₹ 3,45,900 Cr", peRatio: "19.20", divYield: "0.11%", high52: 1950.00, low52: 1550.00, description: "Kotak Mahindra Bank Limited is an Indian banking and financial services company headquartered in Mumbai. It offers personal finance, investment banking, life insurance, and wealth management." },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd.", sector: "Automotive", cap: "Large Cap", price: 12100.00, prevClose: 12180.00, marketCap: "₹ 3,80,400 Cr", peRatio: "28.50", divYield: "1.05%", high52: 13000.00, low52: 8900.00, description: "Maruti Suzuki India Limited is the leading passenger car manufacturer in India. It is a subsidiary of Japanese automobile manufacturer Suzuki Motor Corporation, with massive production facilities." },
  { symbol: "NTPC", name: "NTPC Ltd.", sector: "Energy & Power", cap: "Large Cap", price: 360.00, prevClose: 355.40, marketCap: "₹ 3,49,200 Cr", peRatio: "16.40", divYield: "2.10%", high52: 395.00, low52: 185.00, description: "NTPC Limited, formerly known as National Thermal Power Corporation Limited, is an Indian public sector undertaking engaged in the generation of electricity and allied activities." },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd.", sector: "Energy & Conglomerate", cap: "Large Cap", price: 270.00, prevClose: 268.35, marketCap: "₹ 3,39,600 Cr", peRatio: "7.10", divYield: "4.15%", high52: 295.00, low52: 150.00, description: "Oil and Natural Gas Corporation is an Indian crude oil and natural gas multinational public sector undertaking headquartered in New Delhi. It is owned by the Ministry of Petroleum and Natural Gas." },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd.", sector: "Energy & Conglomerate", cap: "Large Cap", price: 3150.00, prevClose: 3120.00, marketCap: "₹ 3,59,100 Cr", peRatio: "98.50", divYield: "0.04%", high52: 3450.00, low52: 1850.00, description: "Adani Enterprises Limited is the flagship company of the Adani Group, a leading multinational conglomerate in India with diverse business divisions including mining, solar, airport operations, road infrastructure, data centers, and water management." },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ Ltd.", sector: "Engineering & Infrastructure", cap: "Large Cap", price: 1350.00, prevClose: 1362.00, marketCap: "₹ 2,91,600 Cr", peRatio: "32.10", divYield: "0.45%", high52: 1480.00, low52: 650.00, description: "Adani Ports and Special Economic Zone Limited is India's largest private multi-port operator. It represents a formidable infrastructure pipeline connecting primary trade routes in the Indian Ocean." },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd.", sector: "Healthcare", cap: "Large Cap", price: 5950.00, prevClose: 5890.00, marketCap: "₹ 85,500 Cr", peRatio: "65.10", divYield: "0.25%", high52: 6870.00, low52: 4520.00, description: "Apollo Hospitals Enterprise Limited is an Indian multinational hospital chain headquartered in Chennai, Tamil Nadu. It is the largest healthcare provider in India." },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd.", sector: "Consumer Durables", cap: "Large Cap", price: 2890.00, prevClose: 2915.00, marketCap: "₹ 2,77,200 Cr", peRatio: "52.40", divYield: "1.55%", high52: 3420.00, low52: 2700.00, description: "Asian Paints Limited is an Indian multinational paint company, headquartered in Mumbai. The company is engaged in the business of manufacturing, selling and distributing paints, coatings, home decor and bath fittings." },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd.", sector: "Automotive", cap: "Large Cap", price: 9100.00, prevClose: 9020.00, marketCap: "₹ 2,57,300 Cr", peRatio: "32.40", divYield: "1.60%", high52: 10100.00, low52: 4600.00, description: "Bajaj Auto Limited is an Indian multinational automotive manufacturing company based in Pune. It manufactures motorcycles, scooters and auto-rickshaws, and is the world's third-largest manufacturer of motorcycles." },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1580.00, prevClose: 1592.00, marketCap: "₹ 2,51,800 Cr", peRatio: "34.10", divYield: "0.06%", high52: 1740.00, low52: 1350.00, description: "Bajaj Finserv Limited is an Indian non-banking financial services company headquartered in Pune. It is focused on lending, asset management, wealth management, and insurance." },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 6850.00, prevClose: 6920.00, marketCap: "₹ 4,24,000 Cr", peRatio: "28.50", divYield: "0.52%", high52: 8190.00, low52: 6010.00, description: "Bajaj Finance Limited is an Indian non-banking financial company headquartered in Pune. It is one of the leading digital lending consumer finance firms in the country." },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation Ltd.", sector: "Energy & Conglomerate", cap: "Large Cap", price: 620.00, prevClose: 610.40, marketCap: "₹ 1,34,500 Cr", peRatio: "5.10", divYield: "4.20%", high52: 688.00, low52: 330.00, description: "Bharat Petroleum Corporation Limited is an Indian public sector undertaking under the ownership of Ministry of Petroleum and Natural Gas, headquartered in Mumbai." },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd.", sector: "FMCG", cap: "Large Cap", price: 5150.00, prevClose: 5110.00, marketCap: "₹ 1,24,000 Cr", peRatio: "58.40", divYield: "1.45%", high52: 5720.00, low52: 4350.00, description: "Britannia Industries Limited is an Indian multinational food and beverage company, headquartered in Bangalore. It is famous for its biscuit brands, including Good Day, Tiger, NutriChoice, and Marie Gold." },
  { symbol: "CIPLA", name: "Cipla Ltd.", sector: "Pharmaceuticals", cap: "Large Cap", price: 1460.00, prevClose: 1450.20, marketCap: "₹ 1,17,800 Cr", peRatio: "28.10", divYield: "0.65%", high52: 1580.00, low52: 910.00, description: "Cipla Limited is an Indian multinational pharmaceutical company, headquartered in Mumbai. Cipla primarily develops medicines to treat respiratory, cardiovascular disease, arthritis, diabetes, weight control and depression." },
  { symbol: "COALINDIA", name: "Coal India Ltd.", sector: "Metals & Mining", cap: "Large Cap", price: 445.00, prevClose: 448.20, marketCap: "₹ 2,74,200 Cr", peRatio: "8.40", divYield: "5.45%", high52: 490.00, low52: 220.00, description: "Coal India Limited is an Indian public sector undertaking coal mining and refining corporative headquartered in Kolkata. It is the largest coal-producing company in the world." },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd.", sector: "Pharmaceuticals", cap: "Large Cap", price: 3850.00, prevClose: 3810.00, marketCap: "₹ 1,02,200 Cr", peRatio: "61.50", divYield: "0.75%", high52: 4250.00, low52: 3150.00, description: "Divi's Laboratories Limited is an Indian multinational pharmaceutical company and producer of active pharmaceutical ingredients (APIs), headquartered in Hyderabad." },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd.", sector: "Pharmaceuticals", cap: "Large Cap", price: 6120.00, prevClose: 6185.00, marketCap: "₹ 1,01,900 Cr", peRatio: "18.20", divYield: "0.60%", high52: 6500.00, low52: 4850.00, description: "Dr. Reddy's Laboratories is an Indian multinational pharmaceutical company located in Hyderabad. The company manufactures and markets a wide range of pharmaceuticals in India and overseas." },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd.", sector: "Automotive", cap: "Large Cap", price: 4580.00, prevClose: 4540.00, marketCap: "₹ 1,25,300 Cr", peRatio: "31.40", divYield: "1.10%", high52: 4930.00, low52: 3160.00, description: "Eicher Motors Limited is an Indian multinational automotive company that manufactures motorcycles and commercial vehicles. Eicher is the parent company of Royal Enfield, a manufacturer of middleweight motorcycles." },
  { symbol: "GRASIM", name: "Grasim Industries Ltd.", sector: "Materials & Cement", cap: "Large Cap", price: 2350.00, prevClose: 2320.00, marketCap: "₹ 1,59,400 Cr", peRatio: "25.10", divYield: "0.45%", high52: 2550.00, low52: 1650.00, description: "Grasim Industries Limited is an Indian manufacturing company headquartered in Mumbai. Grasim is a leading global producer of viscose staple fibre and has diversification in cement and chemical industries." },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd.", sector: "Information Technology", cap: "Large Cap", price: 1340.00, prevClose: 1352.05, marketCap: "₹ 3,63,500 Cr", peRatio: "23.40", divYield: "3.20%", high52: 1680.00, low52: 1010.00, description: "HCL Technologies Limited, d/b/a HCLTech, is an Indian multinational information technology services and consulting company headquartered in Noida. It is a subsidiary of HCL Enterprise." },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Company Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 590.00, prevClose: 595.40, marketCap: "₹ 1,26,900 Cr", peRatio: "75.10", divYield: "0.35%", high52: 690.00, low52: 485.00, description: "HDFC Life Insurance Company Limited is a long-term life insurance provider headquartered in Mumbai, offering individual and group insurance solutions." },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd.", sector: "Automotive", cap: "Large Cap", price: 4450.00, prevClose: 4410.80, marketCap: "₹ 88,900 Cr", peRatio: "22.10", divYield: "2.10%", high52: 4950.00, low52: 2600.00, description: "Hero MotoCorp Limited, formerly Hero Honda, is an Indian multinational motorcycle and scooter manufacturer headquartered in New Delhi. It is the largest two-wheeler manufacturer in the world." },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd.", sector: "Metals & Mining", cap: "Large Cap", price: 610.00, prevClose: 605.20, marketCap: "₹ 1,36,800 Cr", peRatio: "14.50", divYield: "0.60%", high52: 660.00, low52: 390.00, description: "Hindalco Industries Limited is an Indian aluminum and copper manufacturing company. It is a subsidiary of the Aditya Birla Group, with operations in 11 countries." },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1430.00, prevClose: 1445.00, marketCap: "₹ 1,11,400 Cr", peRatio: "13.20", divYield: "1.05%", high52: 1690.00, low52: 1010.00, description: "IndusInd Bank Limited is a new generation Indian bank headquartered in Mumbai. The bank offers commercial, transactional and electronic banking products and services." },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd.", sector: "Metals & Mining", cap: "Large Cap", price: 890.00, prevClose: 878.50, marketCap: "₹ 2,17,300 Cr", peRatio: "19.50", divYield: "0.45%", high52: 950.00, low52: 680.00, description: "JSW Steel Limited is an Indian multinational steel making company based in Mumbai, Maharashtra. It is a flagship company of the JSW Group and one of the largest private steel manufacturers in India." },
  { symbol: "LTIM", name: "LTIMindtree Ltd.", sector: "Information Technology", cap: "Large Cap", price: 4820.00, prevClose: 4875.00, marketCap: "₹ 1,42,800 Cr", peRatio: "31.20", divYield: "1.15%", high52: 6500.00, low52: 4120.00, description: "LTIMindtree Limited is a leading global technology consulting and digital solutions company, helping more than 700 clients to succeed in an exhausting digital world." },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd.", sector: "Automotive", cap: "Large Cap", price: 2510.00, prevClose: 2485.40, marketCap: "₹ 3,12,600 Cr", peRatio: "26.50", divYield: "0.65%", high52: 2750.00, low52: 1150.00, description: "Mahindra & Mahindra Limited is an Indian multinational automotive manufacturing conglomerate corporation headquartered in Mumbai. It is one of the largest vehicle manufacturers by production in India." },
  { symbol: "NESTLEIND", name: "Nestle India Ltd.", sector: "FMCG", cap: "Large Cap", price: 2520.00, prevClose: 2545.00, marketCap: "₹ 2,42,800 Cr", peRatio: "75.40", divYield: "1.15%", high52: 2770.00, low52: 1950.00, description: "Nestle India Limited is the Indian subsidiary of Nestle, which is a Swiss multinational company. The company manufactures products under famous food brands including Maggi, Nescafe, and KitKat." },
  { symbol: "POWERGRID", name: "Power Grid Corporation of India Ltd.", sector: "Energy & Power", cap: "Large Cap", price: 310.00, prevClose: 312.40, marketCap: "₹ 2,88,200 Cr", peRatio: "17.10", divYield: "3.55%", high52: 348.00, low52: 172.00, description: "Power Grid Corporation of India Limited is an Indian public sector undertaking engaged mainly in transmission of bulk power across different states of India." },
  { symbol: "SBILIFE", name: "SBI Life Insurance Company Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 1420.00, prevClose: 1405.00, marketCap: "₹ 1,42,100 Cr", peRatio: "72.40", divYield: "0.15%", high52: 1560.00, low52: 1080.00, description: "SBI Life Insurance Company Limited is a leading joint venture life insurance company in India between State Bank of India and French financial institution BNP Paribas Cardif." },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd.", sector: "Pharmaceuticals", cap: "Large Cap", price: 1490.00, prevClose: 1475.25, marketCap: "₹ 3,57,500 Cr", peRatio: "35.20", divYield: "0.65%", high52: 1620.00, low52: 950.00, description: "Sun Pharmaceutical Industries Limited is an Indian multinational pharmaceutical company headquartered in Mumbai, Maharashtra, that manufactures and sells pharmaceutical formulations and active pharmaceutical ingredients (APIs)." },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd.", sector: "FMCG", cap: "Large Cap", price: 1110.00, prevClose: 1102.30, marketCap: "₹ 1,05,400 Cr", peRatio: "42.50", divYield: "0.75%", high52: 1250.00, low52: 710.00, description: "Tata Consumer Products Limited is an Indian multinational fast-moving consumer goods company headquartered in Kolkata. It is a focused food and beverage division of the Tata Group." },
  { symbol: "TECHM", name: "Tech Mahindra Ltd.", sector: "Information Technology", cap: "Large Cap", price: 1280.00, prevClose: 1290.40, marketCap: "₹ 1,24,600 Cr", peRatio: "25.10", divYield: "2.35%", high52: 1430.00, low52: 980.00, description: "Tech Mahindra is an Indian multinational information technology services and consulting company. Part of the Mahindra Group, the company is headquartered in Pune and has its registered office in Mumbai." },
  { symbol: "TITAN", name: "Titan Company Ltd.", sector: "Consumer Durables", cap: "Large Cap", price: 3250.00, prevClose: 3280.00, marketCap: "₹ 2,88,600 Cr", peRatio: "82.50", divYield: "0.28%", high52: 3880.00, low52: 2350.00, description: "Titan Company Limited is an Indian luxury goods company that mainly manufactures fashion accessories such as watches, jewelry and eyewear. Part of the Tata Group, it is headquartered in Bangalore." },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd.", sector: "Materials & Cement", cap: "Large Cap", price: 9850.00, prevClose: 9750.00, marketCap: "₹ 2,84,300 Cr", peRatio: "38.40", divYield: "0.40%", high52: 10500.00, low52: 6900.00, description: "UltraTech Cement Limited is the largest manufacturer of grey cement, ready mix concrete (RMC) and white cement in India. It is a core manufacturing subsidiary of the Aditya Birla Group." },
  { symbol: "UPL", name: "UPL Ltd.", sector: "Chemicals", cap: "Large Cap", price: 510.00, prevClose: 512.40, marketCap: "₹ 38,400 Cr", peRatio: "15.40", divYield: "1.95%", high52: 710.00, low52: 450.00, description: "UPL Limited, formerly United Phosphorus Limited, is an Indian multinational company that manufactures and markets agrochemicals, industrial chemicals, chemical intermediates, and specialty chemicals." },
  { symbol: "PAYTM", name: "One 97 Communications Ltd. (Paytm)", sector: "Banking & Finance", cap: "Mid Cap", price: 420.00, prevClose: 410.50, marketCap: "₹ 26,600 Cr", peRatio: "N/A", divYield: "0.00%", high52: 990.00, low52: 310.00, description: "One 97 Communications Limited is an Indian multinational technology company specializing in digital payment systems, e-commerce, and finance, widely known for its flagship brand Paytm." },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures Ltd. (Nykaa)", sector: "Consumer Services", cap: "Mid Cap", price: 175.00, prevClose: 172.40, marketCap: "₹ 50,000 Cr", peRatio: "115.00", divYield: "0.00%", high52: 220.00, low52: 110.00, description: "FSN E-Commerce Ventures Limited, doing business as Nykaa, is an Indian lifestyle retail platform for beauty, wellness, and fashion, founded by Falguni Nayar." },
  { symbol: "IDEA", name: "Vodafone Idea Ltd.", sector: "Telecommunications", cap: "Mid Cap", price: 13.50, prevClose: 13.80, marketCap: "₹ 65,400 Cr", peRatio: "N/A", divYield: "0.00%", high52: 18.50, low52: 6.80, description: "Vodafone Idea Limited is an Indian telecom operator headquartered in Mumbai and Gandhinagar. It is an active nationwide GSM operator offering 2G, 3G, and 4G services." },
  { symbol: "YESBANK", name: "Yes Bank Ltd.", sector: "Banking & Finance", cap: "Mid Cap", price: 24.10, prevClose: 24.30, marketCap: "₹ 75,500 Cr", peRatio: "38.20", divYield: "0.00%", high52: 32.80, low52: 14.10, description: "Yes Bank Limited is an Indian private sector bank, headquartered in Mumbai. It offers a wide array of retail, corporate, and investment banking services across the country." },
  { symbol: "TATAPOWER", name: "Tata Power Company Ltd.", sector: "Energy & Power", cap: "Large Cap", price: 435.00, prevClose: 428.40, marketCap: "₹ 1,38,900 Cr", peRatio: "32.40", divYield: "0.45%", high52: 460.00, low52: 185.00, description: "Tata Power Company Limited is an Indian electric utility company based in Mumbai, Maharashtra, India and is part of the Tata Group. The core business is to generate, transmit and distribute electricity." },
  { symbol: "SUZLON", name: "Suzlon Energy Ltd.", sector: "Energy & Power", cap: "Mid Cap", price: 55.20, prevClose: 54.10, marketCap: "₹ 75,200 Cr", peRatio: "45.00", divYield: "0.00%", high52: 68.00, low52: 12.00, description: "Suzlon Energy Limited is an Indian multinational wind turbine manufacturer headquartered in Pune, India. It was formerly ranked by MAKE as the world's fifth-largest wind turbine supplier." },
  { symbol: "IRFC", name: "Indian Railway Finance Corporation Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 178.00, prevClose: 176.45, marketCap: "₹ 2,32,500 Cr", peRatio: "35.10, ", divYield: "1.20%", high52: 229.00, low52: 32.00, description: "Indian Railway Finance Corporation is an Indian public sector undertaking owned by the Indian Railways, under the administrative control of the Ministry of Railways." },
  { symbol: "RVNL", name: "Rail Vikas Nigam Ltd.", sector: "Engineering & Infrastructure", cap: "Mid Cap", price: 385.00, prevClose: 374.20, marketCap: "₹ 80,200 Cr", peRatio: "42.10", divYield: "0.55%", high52: 425.00, low52: 110.00, description: "Rail Vikas Nigam Limited is an Indian public sector undertaking which works as the construction arm of the Ministry of Railways for project implementation and transportation infrastructure." },
  { symbol: "NHPC", name: "NHPC Ltd.", sector: "Energy & Power", cap: "Mid Cap", price: 102.00, prevClose: 100.80, marketCap: "₹ 1,02,400 Cr", peRatio: "24.10", divYield: "1.80%", high52: 118.00, low52: 42.00, description: "NHPC Limited, formerly National Hydroelectric Power Corporation, is an Indian public sector hydropower utility owned by the Ministry of Power, Government of India." },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure Ltd.", sector: "Engineering & Infrastructure", cap: "Mid Cap", price: 88.00, prevClose: 86.40, marketCap: "₹ 53,100 Cr", peRatio: "N/A", divYield: "0.00%", high52: 101.00, low52: 40.00, description: "GMR Airports Infrastructure Limited operates airports in India and international territories, maintaining premier transport gateways including New Delhi and Hyderabad airports." },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Banking & Finance", cap: "Large Cap", price: 122.00, prevClose: 124.50, marketCap: "₹ 1,34,300 Cr", peRatio: "14.20", divYield: "1.25%", high52: 142.00, low52: 50.00, description: "Punjab National Bank is an Indian public sector bank headquartered in New Delhi. It is the second-largest public sector bank in India, both in terms of business and branch network." },
  { symbol: "UNIONBANK", name: "Union Bank of India", sector: "Banking & Finance", cap: "Mid Cap", price: 142.00, prevClose: 140.80, marketCap: "₹ 1,08,300 Cr", peRatio: "9.10", divYield: "2.10%", high52: 172.00, low52: 68.00, description: "Union Bank of India is one of the largest government-owned banks in India. It is under the ownership of the Ministry of Finance with a robust network of digital banking channels." },
  { symbol: "CANBK", name: "Canara Bank", sector: "Banking & Finance", cap: "Large Cap", price: 118.00, prevClose: 119.50, marketCap: "₹ 1,07,100 Cr", peRatio: "8.50", divYield: "2.50%", high52: 129.00, low52: 58.00, description: "Canara Bank is an Indian public sector bank under the ownership of the Ministry of Finance, Government of India, headquartered in Bengaluru, Karnataka." },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Banking & Finance", cap: "Large Cap", price: 265.00, prevClose: 268.20, marketCap: "₹ 1,37,100 Cr", peRatio: "7.80", divYield: "2.25%", high52: 298.00, low52: 162.00, description: "Bank of Baroda is an Indian public sector banking and financial services company headquartered in Vadodara, Gujarat. It is the third-largest public sector bank in India." },
  { symbol: "SAIL", name: "Steel Authority of India Ltd.", sector: "Metals & Mining", cap: "Mid Cap", price: 148.00, prevClose: 145.40, marketCap: "₹ 61,100 Cr", peRatio: "18.50", divYield: "1.35%", high52: 178.00, low52: 82.00, description: "Steel Authority of India Limited is an Indian public sector steel-making company based in New Delhi. It is a government-owned enterprise with massive integrated steel plants across India." },
  { symbol: "NMDC", name: "Metals & Mining", cap: "Mid Cap", price: 235.00, prevClose: 231.80, marketCap: "₹ 68,800 Cr", peRatio: "10.40", divYield: "2.40%", high52: 286.00, low52: 105.00, description: "NMDC Limited, formerly National Mineral Development Corporation, is an Indian public sector mineral producer owned by the Ministry of Steel, Government of India." },
  { symbol: "GAIL", name: "GAIL (India) Ltd.", sector: "Energy & Power", cap: "Large Cap", price: 205.00, prevClose: 202.15, marketCap: "₹ 1,34,700 Cr", peRatio: "12.40", divYield: "2.15%", high52: 232.00, low52: 102.00, description: "GAIL Limited is the largest state-owned natural gas processing and distribution company in India, headquartered in New Delhi, operating nationwide pipelines." },
  { symbol: "BHEL", name: "Bharat Heavy Electricals Ltd.", sector: "Engineering & Infrastructure", cap: "Mid Cap", price: 285.00, prevClose: 281.40, marketCap: "₹ 99,200 Cr", peRatio: "N/A", divYield: "0.00%", high52: 325.00, low52: 80.00, description: "Bharat Heavy Electricals Limited is an Indian public sector engineering and manufacturing company based in New Delhi. It is the largest power generation equipment manufacturer in India." },
  { symbol: "JIOFIN", name: "Jio Financial Services Ltd.", sector: "Banking & Finance", cap: "Large Cap", price: 345.00, prevClose: 341.20, marketCap: "₹ 2,19,200 Cr", peRatio: "54.10", divYield: "0.00%", high52: 395.00, low52: 215.00, description: "Jio Financial Services Limited, originally spun off from Reliance Industries, operates high-impact financial products spanning lending, digital payments, and insurance." },
  { symbol: "RPOWER", name: "Reliance Power Ltd.", sector: "Energy & Power", cap: "Small Cap", price: 28.50, prevClose: 28.10, marketCap: "₹ 11,400 Cr", peRatio: "N/A", divYield: "0.00%", high52: 34.50, low52: 9.20, description: "Reliance Power Limited, part of the Reliance ADAG Group, is an Indian power generation company specializing in coal-fired, gas, hydroelectric, and solar power facilities." },
  { symbol: "RELINFRA", name: "Reliance Infrastructure Ltd.", sector: "Engineering & Infrastructure", cap: "Small Cap", price: 198.00, prevClose: 195.40, marketCap: "₹ 7,800 Cr", peRatio: "N/A", divYield: "0.00%", high52: 245.00, low52: 115.00, description: "Reliance Infrastructure Limited is an Indian private sector company engaged in power generation, transmission, distribution and running core infrastructure projects such as metro rails and roads." },
  { symbol: "RHFL", name: "Reliance Home Finance Ltd.", sector: "Banking & Finance", cap: "Small Cap", price: 4.20, prevClose: 4.15, marketCap: "₹ 200 Cr", peRatio: "N/A", divYield: "0.00%", high52: 6.10, low52: 1.80, description: "Reliance Home Finance Limited is an Indian non-banking financial company offering customized home loan and housing finance plans to individuals and corporate borrowers." },
  { symbol: "RNAVAL", name: "Reliance Naval and Engineering Ltd.", sector: "Engineering & Infrastructure", cap: "Small Cap", price: 3.10, prevClose: 3.05, marketCap: "₹ 150 Cr", peRatio: "N/A", divYield: "0.00%", high52: 4.80, low52: 1.25, description: "Reliance Naval and Engineering Limited is an Indian heavy engineering, shipyard and shipbuilding company based in Pipavav, Gujarat. It is specialized in defense vessel construction." }
];

export function getNseStockTemplate(symbol) {
  const cleanSymbol = symbol.toUpperCase().trim();
  
  // Find in our pre-defined 75 popular stocks
  const found = ALL_NSE_STOCKS.find(s => s.symbol === cleanSymbol);
  
  if (found) {
    const basePrice = found.price;
    const prevClose = found.prevClose || Number((basePrice * (0.95 + Math.random() * 0.1)).toFixed(2));
    const marketCap = found.marketCap || `₹ ${Math.floor(15000 + Math.random() * 85000)} Cr`;
    const peRatio = found.peRatio || (10 + (basePrice % 40)).toFixed(2);
    const divYield = found.divYield || `${(0.5 + (basePrice % 4) * 0.4).toFixed(2)}%`;
    const high52 = found.high52 || Number((basePrice * 1.3).toFixed(2));
    const low52 = found.low52 || Number((basePrice * 0.7).toFixed(2));
    
    return {
      symbol: cleanSymbol,
      name: found.name,
      sector: found.sector,
      cap: found.cap || "Large Cap",
      price: basePrice,
      prevClose,
      marketCap,
      peRatio,
      divYield,
      high52,
      low52,
      description: found.description || `${found.name} is a prominent player in the ${found.sector} sector, actively traded on the National Stock Exchange (NSE).`
    };
  }
  
  // Deterministic generator for completely custom symbols!
  let hash = 0;
  for (let i = 0; i < cleanSymbol.length; i++) {
    hash = cleanSymbol.charCodeAt(i) + ((hash << 5) - hash);
  }
  hash = Math.abs(hash);
  
  const sectors = [
    "Information Technology", 
    "Banking & Finance", 
    "Energy & Power", 
    "Automotive", 
    "Pharmaceuticals", 
    "FMCG", 
    "Engineering & Infrastructure", 
    "Telecommunications", 
    "Materials & Cement"
  ];
  const sector = sectors[hash % sectors.length];
  
  const caps = ["Large Cap", "Mid Cap", "Small Cap"];
  const cap = caps[hash % caps.length];
  
  // Deterministic price between 25 and 1500
  const price = Number((25 + (hash % 1475) + (hash % 100) / 100).toFixed(2));
  const prevClose = Number((price * (0.97 + (hash % 6) / 100)).toFixed(2));
  
  const suffixes = ["Industries Ltd.", "India Ltd.", "Enterprises Ltd.", "Solutions Ltd.", "Global Ltd."];
  const suffix = suffixes[hash % suffixes.length];
  const name = `${cleanSymbol} ${suffix}`;
  
  const mcapVal = hash % 2 === 0 
    ? `${(5000 + (hash % 45000)).toLocaleString("en-IN")}` 
    : `${(500 + (hash % 4500)).toLocaleString("en-IN")}`;
  const marketCap = `₹ ${mcapVal} Cr`;
  
  const peRatio = (12 + (hash % 38) + (hash % 10) / 10).toFixed(2);
  const divYield = `${((hash % 15) / 5).toFixed(2)}%`;
  
  const high52 = Number((price * (1.15 + (hash % 30) / 100)).toFixed(2));
  const low52 = Number((price * (0.75 + (hash % 15) / 100)).toFixed(2));
  
  const description = `${name} is a publicly traded enterprise listed on the National Stock Exchange (NSE). The company is a key competitor in the ${sector} sector under active trade and paper simulation.`;
  
  return {
    symbol: cleanSymbol,
    name,
    sector,
    cap,
    price,
    prevClose,
    marketCap,
    peRatio,
    divYield,
    high52,
    low52,
    description
  };
}
